version: "3"
services:
  nginx:
    #build:
      # context: ./services/nginx
    image: registry.cn-hangzhou.aliyuncs.com/hijkoo/cloud-nginx:v1
    container_name: nginx
    ports:
        - "80:80"
        - "8090:8090"
    volumes:
        - ${SOURCE_DIR}:/usr/share/nginx/html:ro
        - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
        - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
        - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
        TZ: "$TZ"
    depends_on:
        - php
    restart: always
    networks:
       - default
  php:
    image: registry.cn-hangzhou.aliyuncs.com/hijkoo/cloud-php:v1
    container_name: php
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${SUPERVISOR_LOG}:/var/log/supervisor/:rw
      - ${SUPERVISOR_CONFIG}:/etc/supervisor/conf.d/:rw
      - ${SUPERVISOR_CONF_FILE}:/etc/supervisor/supervisord.conf:ro
      - ${SSH_KEY_DIR}:/root/.ssh:rw
    environment:
        TZ: "$TZ"
    restart: always
    ports:
      - "9000:9000"
    cap_add:
      - SYS_PTRACE
    command:
      - /bin/sh
      - -c
      - |
        crond
        php-fpm &
        supervisord -n -c /etc/supervisor/supervisord.conf
    networks:
      - default
  node15:
    build:
      context: ./services/node15
      args:
        NODE15_VERSION: node:${NODE15_VERSION}-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        TZ: "$TZ"
    container_name: node15
    volumes:
      - ${SOURCE_DIR}:/www/:cached
    restart: always
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - default
  redis:
    image: redis
    restart: always
    hostname: redis
    container_name: redis
    privileged: true
    ports:
      - 6379:6379
    environment:
      TZ: "$TZ"
    volumes:
      - ${REDIS_DATA}:/data
      - ${REDIS_CONF_FILE}:/etc/redis/redis.conf
      - ${REDIS_LOG_DIR}:/logs
    command: ["redis-server","/etc/redis/redis.conf"]
    networks:
      - default
  mqtt:
    image: emqx/emqx:v4.0.0
    restart: always
    container_name: mqtt
    environment:
      TZ: "$TZ"
    volumes:
      - ${EMQX_AUTH_MYSQL_CONF_FILE}:/opt/emqx/etc/plugins/emqx_auth_mysql.conf
      - ${EMQX_CONF_FILE}:/opt/emqx/etc/emqx.conf
    networks:
    - default
networks:
  default:
